### ISSUE TITLE
Support "tags" on upload and export

### ISSUE THREAD

**Issue by baschny** [marstonstudio/poeditor-connector#1]
Hi, great tool, thanks for it!

We have a poeditor project which contains labels for different components. We use "tags" to differentiate the components, and thus it would be helpful to be able set this tag on "upload" and "export" filtering by this tag.

Maybe also use the feature of tagging "obsolete" or "new" terms when uploading (see https://poeditor.com/api_reference/#upload) while doing this.

Just make these tags "configurable" in the poeditor.json.

**Comment by marstonstudio** [comment]
deployed to npm.js as version 0.8.0
