### ISSUE TITLE
Read APITOKEN from env

### ISSUE THREAD

**Issue by baschny** [marstonstudio/poeditor-connector#2]
We want to include the projects `poeditor.json` configuration to GIT, but we don't want to have the API key hardcoded inside.

It would be helpful to be able to override the API key through a environment variable (i.e. POEDITOR_APITOKEN) so that we could make this information part of the CI process (or customizable per developer environment).

**Comment by marstonstudio** [comment]
deployed to npm.js as version 0.8.0
