### ISSUE TITLE
Allow other settings with "upload" endpoint

### ISSUE THREAD

**Issue by baschny** [marstonstudio/poeditor-connector#3]
Currently the upload routine has these hardcoded settings:

* updating: "terms_definitions"
* language: "en"

Only this is configurable:
* sync_terms

Make `updating` and `language` configurable (fallback to these defaults if not set), and also add configuration options for `overwrite` and `fuzzy_trigger`.

See API reference: 
https://poeditor.com/api_reference/#upload

**Comment by marstonstudio** [comment]
deployed to npm.js as version 0.8.0
